# SPDX-License-Identifier: Apache-2.0

if(CONFIG_64BIT)
  if(CONFIG_FPU)
    prj_compile_options(-march=rv64gc)
    prj_compile_options(-mabi=lp64d)
  else()
    prj_compile_options(-march=rv64imac)
    prj_compile_options(-mabi=lp64)
  endif()
  prj_compile_options(-mcmodel=medany)
endif()

if(CONFIG_32BIT)
  if(CONFIG_FPU)
    prj_compile_options(-march=rv32imafc)
    prj_compile_options(-mabi=ilp32f)
  else()
    prj_compile_options(-march=rv32imac)
    prj_compile_options(-mabi=ilp32)
  endif()
endif()
